version: '3.8'

services:
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-prod
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=production