version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dormbuddy-frontend
    ports:
      - "3005:3005"
    restart: always
    networks:
      - dormbuddy-network
      - default

networks:
  dormbuddy-network:
    external: true
  default: