version: '3.8'

services:
  # Development service
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  # Production service
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-prod
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=production